### ISSUE TITLE
Settle on standard CAN transceiver

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Hardware#29]
We should identify the default part.

**Comment by pkocmoud** [comment]
When developing the CANESC 1.6 it was suggested that we choose a part which was 
ISO 11898-2 compliant. https://en.wikipedia.org/wiki/CAN_bus#Standards Therefore we settled on the Linear LTC2875 http://www.linear.com/product/LTC2875 . It seems to work fine.

**Comment by nickarsov** [comment]
Also a very good solution with best performance/price is TJA1051TK3/118

**Comment by LorenzMeier** [comment]
@CarlOlsson Sounds like the TJA is your part then.

**Comment by proficnc** [comment]
Yes, this is the Transceiver that I am using....

**Comment by CarlOlsson** [comment]
Ok perfect! Thanks for the info

**Comment by CarlOlsson** [comment]
I cant find the TJA1051TK3/118 in the [NXP eagle library](http://www.element14.com/community/docs/DOC-64270/l/nxp-cad-library-for-cadsoft-eagle-software) or the [pixhawk2.lbr](https://github.com/PX4/Hardware/blob/master/pixhawk2.lbr) or in https://github.com/pixhawk/Hardware/tree/master/eagle/libraries/eagle.

If I have not missed it I will create the part but where shall I add it to make it easier for future designers?

**Comment by LorenzMeier** [comment]
Pixhawk 2 libraries. The current generation boards are done in Altium.

**Comment by CarlOlsson** [comment]
Ok thx!

**Comment by pavel-kirienko** [comment]
TJA1051 is good, but in certain cases it is preferable to use a 3.3V transceiver. In this case I would recommend [SN65HVD232](http://www.ti.com/product/sn65hvd232) - it is cheap and automotive grade; the downside is that it's only available in SO8 which is huge.

[LTC2875](http://www.linear.com/product/LTC2875) Phillip mentioned is another 3.3V alternative in a small package, but its cost may be prohibitive.

**Comment by proficnc** [comment]
Agreed on the 3.3 vs 5v issue.

May I suggest that rather than trying to define a standard here... We just list devices that have been verified, with their strengths and weaknesses listed? 

As long as they perform the job they are required to do, the choice should be up to the needs of the designer.

We should list some tests, ie, is it non blocking when a micro sets pins to locked values etc....  So maybe add a blacklist of parts that we will not accept if proven not to be up to standard

**Comment by CarlOlsson** [comment]
I agree.
The reason to why I asked in the first place was that I wanted to use a design already proven to work.
The list so far:
- Olimexino: **MCP2551-I/SN**
- Pixhawk ESC 1.6: **LTC2875**
- Pixhawk ESC 1.4b: **MAX3051EKA**
- s2740vc ESC and XRacer: **TJA1051TK3/118**

**Comment by LorenzMeier** [comment]
@CarlOlsson What was the final choice?

**Comment by proficnc** [comment]
The final choice was a whitelist and blacklist... As different components may suit different applications.

Anything that is deemed unsuitable should be blacklisted

**Comment by nickarsov** [comment]
To me, the white list currently looks like:
TJA1051TK3/118
LTC2875

**Comment by proficnc** [comment]
Agreed

**Comment by LorenzMeier** [comment]
Thanks for the feedback Phil! I'll get that into the Dronecode wiki. What voltage are these designed for - 3.3V?

**Comment by proficnc** [comment]
The Can side is always 5v, but the secondary on the TJA105 is 3.3v 

Need to check the others

This is the one I am using now for all new designs

**Comment by LorenzMeier** [comment]
Noted here: https://wiki.dronecode.org/workgroup/connectors/start?&#can_tranceivers
