### ISSUE TITLE
When to terminate the CAN Bus?

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Hardware#31]
*"According to ISO 11898, placing the termination resistor on a
node must be avoided because the bus lines lose termination if the node is disconnected from the bus.”*

As far as I understand the s2740vc ESC:s are internally terminated. Doesn’t this mean that they “have” to be placed at the end of the bus?

**Comment by pavel-kirienko** [comment]
To the best of my knowledge s2740vs do not terminate the bus, it would be pointless. Generally you have to use a termination plug like [this one](http://nicadrone.com/index.php?id_product=54&controller=product).

**Comment by CarlOlsson** [comment]
Ok thanks, as you said, makes more sense
