### ISSUE TITLE
Pixracer: PPM pin output resistor value

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Hardware#38]
@nickarsov @pkocmoud @kd0aij I'm tracking this here for now. We can't seem to be using 470R for the backwards direction, we need to use something with much higher resistance, e.g. 1.5K or 2.2K. We need to try it against real hardware.

Can you please attach (just drag images onto the text pane to attach) scope shots of the port?

**Comment by pkocmoud** [comment]
DSM 470R
![image](https://cloud.githubusercontent.com/assets/7053372/12345098/339a0274-bb0a-11e5-9eb0-8b79f95f9ecd.png)

**Comment by pkocmoud** [comment]
DSM Open Resistor
![image](https://cloud.githubusercontent.com/assets/7053372/12345189/10456e7a-bb0b-11e5-936f-aa96d0b1e4a5.png)

**Comment by pkocmoud** [comment]
DSM R200 = 1.8K
(RC and Bind works)
![image](https://cloud.githubusercontent.com/assets/7053372/12345632/57c11532-bb11-11e5-94d6-76a9e7375cb5.png)

**Comment by pkocmoud** [comment]
DSM R200 = 2.2K
(RC works and Bind does not)
![image](https://cloud.githubusercontent.com/assets/7053372/12345739/92ac494a-bb12-11e5-9d2c-d2720cd188c0.png)

**Comment by pkocmoud** [comment]
My suggestion is continue testing with the 1.8K resistor.

**Comment by nickarsov** [comment]
So, PPM ( PWM->PPM converter ) works with both 1k8 and 2k2, but 2Y must be LOW ( FMU_RC_OUTPUT must be LOW when using with PPM/Spektrum sat ).

![r200_1k8_2k2_ppm](https://cloud.githubusercontent.com/assets/5420053/12348620/a94816ca-bb71-11e5-9d59-25c7e2cf4e1c.png)

**Comment by LorenzMeier** [comment]
As Nick says we have to re-test to make sure we can reach 3.3V and 0V. In your scope shots the signal is still at 1V, which seems a stretch for robustness.

**Comment by nickarsov** [comment]
Lorenz, can you please fix the FMU_RC_OUTPUT = LOW when using PPM/Spektrum. With this fix I'm sure we can go with 1k8 without problems.

**Comment by LorenzMeier** [comment]
I'll leave that to Mark to not confuse your workflow. @kd0aij Can you test that with Phil / Nick? Please re-share the analyser shots here so we can do a final review.

**Comment by kd0aij** [comment]
@LorenzMeier We're seeing good logic levels on RC_INPUT with a variety of receivers and R200 as a 1.8K pulldown. But DSM binding is working only with clones, not authentic Spektrum satellites. The timing precision of the bind pulses is poor with fmuv4, but good with fmuv2. I'm confused by that, since it looks like the same method is being called in both cases (dsm.c::dsm_bind)

**Comment by kd0aij** [comment]
latest test config is here: https://github.com/PX4/Firmware/issues/3513

**Comment by LorenzMeier** [comment]
@kd0aij @pkocmoud @nickarsov Per my last discussion with Phil we propose to abandon S.BUS output and pairing for the first rev. Both are fringe use cases which have *not* been promised to the community or customers.

**Comment by LorenzMeier** [comment]
Fixed in final HW rev.

**Comment by LorenzMeier** [comment]
@pkocmoud What did you end up using in the final HW rev on populated boards? Did this get reflected into a design revision on the schematics for R12 (or whatever the one is which is in production)?

**Comment by pkocmoud** [comment]
R12 this resistor is not populated. The downside is R12 boards cannot command the Spektrum satellites into bind mode. R14, the output was re-routed to not go thru the signal inverter. DNP is listed on both R12 and R14 schematics for the resistor in question.
