### ISSUE TITLE
Include microSD card in Kit

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Hardware#48]
@pkocmoud @nickarsov APM and PX4 both boot into "debug" mode without the microSD card inserted. So unexperienced users who do not insert a card will not be able to connect to the board.

Which essentially means you need to bundle one, because the product is non-functioning without. Hobby king and 3DR both include a card in their default kits.

**Comment by pkocmoud** [comment]
This is done. All new orders will include an 8GB Class 4 microSD card.

**Comment by olibye** [comment]
I ordered my pixracer via AUAV on 12 March 2016 received it **without** a microSD card.
