### ISSUE TITLE
Pixracer: Potential power sequencing issue on GPS port

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Hardware#49]
@nickarsov @pkocmoud The airspeed sensor browns out on boot. The most likely reason is that the power sequencing goes bad during boot.

It only happens when powered through battery, it doesn't happen when powered through USB.

How does the 5V rail plot look like on boot? Please do not offer any judgements, I just want to see the real data. 3 plots:

1) USB power applied
2) Battery power applied
3) A sequence of wiggling the power connector of the battery

**Comment by LorenzMeier** [comment]
So it seems like connecting battery "kills" the sensor. Which seems absurd.

Maybe the device went into a bad state when we powered it reverse.

**Comment by tumbili** [comment]
Correct, having usb connected the driver works. Connecting power without removing the usb cable kills the driver.

**Comment by pkocmoud** [comment]
![5vduringboot](https://cloud.githubusercontent.com/assets/7053372/12425551/eb4c4038-be9a-11e5-82b5-c26071277f5c.png)

Power Up using Battery, connecting and disconnecting USB, Battery remains connected until the end.

**Comment by LorenzMeier** [comment]
@pkocmoud It would be great if you could try to repro with one of these: http://www.hobbyking.com/hobbyking/store/%5F%5F62752%5F%5FHKPilot%5F32%5FDigital%5FAir%5FSpeed%5FSensor%5FAnd%5FPitot%5FTube%5FSet.html

**Comment by pkocmoud** [comment]
"repro"? I have the 3DR Version to test with.

**Comment by tumbili** [comment]
@pkocmoud That would be great.

**Comment by pkocmoud** [comment]
![5vduringbootonmaster](https://cloud.githubusercontent.com/assets/7053372/12426214/40da0fd2-be9e-11e5-84e2-f4590a4ad327.png)
Recorded while loaded with Master.

**Comment by pkocmoud** [comment]
No Brown Outs Detected. The PixRacer power supply is solid during our tests.

**Comment by LorenzMeier** [comment]
@tumbili If you comment out this line, does it work for you?
https://github.com/PX4/Firmware/blob/0e0c1302e41abc75e83bd3b0a324bead952f8a16/src/drivers/meas_airspeed/meas_airspeed.cpp#L228

**Comment by tumbili** [comment]
@LorenzMeier same thing

**Comment by LorenzMeier** [comment]
Odd. It has to be somewhere there.

**Comment by LorenzMeier** [comment]
So my 2nd board has an all working sensor. We have now 3 boards:

1): 0-1.8V on the 5V rail
2): Romans board: 5V on GPS rail, but no airspeed sensor signal when powered via the 3DR power module
3): Completely working when powered at 5.3V through a lab power supply

The only thing I haven't tried yet is what happens when the sensing / ADC pins are active, as I have no power module.

I certainly have a bad board, not sure yet about the causality of the other two items.

**Comment by tumbili** [comment]
@LorenzMeier Is 5.3 a magic value? Does is also work with 5V?

**Comment by LorenzMeier** [comment]
Your power module is outputting 5.3V. Which is why I chose it.

**Comment by nickarsov** [comment]
Yes, it works with 5V too, because the USB can't supply 5.3V

**Comment by LorenzMeier** [comment]
Nick, rather than speculating it would be good if you could work out how I can return the electrically bad board to your for inspection.

**Comment by nickarsov** [comment]
Lorenz, 
Speculating with what...I just answered to Roman.
And yes, you can return it back to me for inspection at:
Nick Arsov
8 Konstantin Irechek str., bl.1
4700 Smolyan
Bulgaria

**Comment by LorenzMeier** [comment]
Thanks, will do! I'm closing this as it seems board-specific.

**Comment by LorenzMeier** [comment]
@nickarsov the part you identified has 5V on one side and 0V on the other.

**Comment by LorenzMeier** [comment]
Soldering looks sketchy. I will rework it later today or tomorrow.

**Comment by LorenzMeier** [comment]
This was in fact the airspeed sensor. Still have one board with 1.8V on that port, but that is probably manufacturing QA. Replaced with: https://github.com/PX4/Hardware/issues/55
