### ISSUE TITLE
Pixracer GPS power port: 1.8V output

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Hardware#50]
@pkocmoud @nickarsov @kd0aij I'm measuring 1.8V output on the GPS power port with just the airspeed sensor attached. Can you confirm that? I'm measuring 0V with nothing attached.

**Comment by nickarsov** [comment]
Lorenz, which cable do you use as GPS cable has been totally swapped - both GPS connector and I2C connector. I already notified all users about. Can you send a screenshot of the wiring?

**Comment by LorenzMeier** [comment]
Its not the wiring, I measured the connector pins. I confirmed that my 2nd board provides 5V, so I got a bad board.

**Comment by LorenzMeier** [comment]
Where was the diode that was the wrong way around? Can you mark it in the layout?

**Comment by nickarsov** [comment]
There is just a resettable fuse between 5V and VDD_5V_PERIPH. Does it get
hot?


2016-01-20 11:14 GMT+02:00 Lorenz Meier <notifications@github.com>:

**Comment by nickarsov** [comment]
Picture attached

2016-01-20 11:15 GMT+02:00 Lorenz Meier <notifications@github.com>:

**Comment by nickarsov** [comment]
![pixracer diodes fuses](https://cloud.githubusercontent.com/assets/5420053/12444555/4aacac66-bf68-11e5-91fc-a46c8765c287.png)

**Comment by LorenzMeier** [comment]
Components on the working and non-working board are all oriented exactly the same.

**Comment by nickarsov** [comment]
Maybe the fuse FR101 gets overloaded by some reason...
What is the voltage on its pads?

**Comment by pkocmoud** [comment]
This appears to be a defective board. Please close this issue unless other examples appear.
