### ISSUE TITLE
Pixracer: PB0 (PPM in) should use RC_INPUT, not FMU_RC_INPUT

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Hardware#52]
@nickarsov The connection to PB0 should be straight from the raw and non-inverted signal (RC_INPUT), not from behind the inverter.

Independent on how we do the new inverting circuitry that pattern will allow Spektrum binding.

**Comment by nickarsov** [comment]
Exactly...I have already separated the two lines in RC13 and RC14

**Comment by LorenzMeier** [comment]
Done.
