### ISSUE TITLE
Pixracer: Clarify ACSP4 scaling for voltage and current

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Hardware#53]
@nickarsov What is the full-scale from 0-3.3V on the voltage and current sense lines? E.g. if the voltage is 3.3V on both lines, what voltage and what current is the sensor seeing?

Note that you need to have the *same* scaling for both power modules, as your users will get terribly confused else. You only should offer a different scaling range for specific sub groups, e.g. very large airframes.

**Comment by pkocmoud** [comment]
The resistor divider is 13k7:1k1. The VMax is 42v.

 42V/14.8*1.1 = 3.12V

The IMax current is 120A (Cooling required above 80A).

120*0.00025*110000/1000 = 3.3V

**Comment by LorenzMeier** [comment]
Done
