### ISSUE TITLE
No GPS -  Pixhawk defective ?

### ISSUE THREAD

**Issue by Tesa99** [PX4/Hardware#58]
Hello,
suddenly the pixhawk stop working with GPS from 3DR . In mission planner I can see NO GPS, and it do not change by the time.

I have tried another GPS Ublox M8N and I have the same problem. 

Is there a procedure I can find out if Pixhawk or the gps modules are defective ?
Compas is working on both.
Thanks,
Radek

**Comment by subzero10** [comment]
Hi, did you solve your problem? I have the same issue. I have an APM 2.6 and a 3DR Pixhawk. The GPS works on the APM but not on the Pixhawk. I want to be sure that everything else is the way it should be (cable, configuration), before attempting to replace my Pixhawk.

**Comment by pkocmoud** [comment]
This seems like an isolated local hardware failure.
