### ISSUE TITLE
FMUv4: Ensure correct power sequencing when powering from USB

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Hardware#59]
@nickarsov We should ensure that any full-sized FMUv4 variant the peripheral power rails default to off and can be actively switched on by the autopilot when it has battery power. This is necessary as some USB lines do not allow enough power to supply the full set of peripherals.

**Comment by nickarsov** [comment]
Already done in the preliminary sch.

**Comment by pkocmoud** [comment]
This was also addressed in the official FMUv4 Standards doc published 4-3-2016.
