### ISSUE TITLE
FMUv4: Power sense pulldowns missing

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Hardware#61]
@nickarsov On FMUv4 2M pull-downs are missing on the voltage and current sense lines. An unpowered ACSP4 reports 2V.

**Comment by nickarsov** [comment]
Lorenz, have a look at the sch ....you'll see R407 and R408......1M resistors

**Comment by LorenzMeier** [comment]
Weird - I saw a 2V level on a board which was not connected to battery. I can't repro now though - closing.
