### ISSUE TITLE
Pixhawk VTOL Issue

### ISSUE THREAD

**Issue by VagishB** [PX4/Hardware#62]
Hi guys,
I am using pixhawk VTOL firmware in my V-tail airframe. Once I switch ON the safety switch, the plane motor is still beeping(I have also BEC in ESC). Could you guys help me?

**Comment by LorenzMeier** [comment]
Is your motor connected to AUX5? There should be a standby signal:
https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/13007_vtol_AAVVT_quad#L41

**Comment by VagishB** [comment]
Yes my motor is connected in Aux 5 only.
