### ISSUE TITLE
in PX4FMUv2.4.5.pdf  PA10 should be labelled USART1_RX not USART1_TX

### ISSUE THREAD

**Issue by kwikius** [PX4/Hardware#65]
In sheet labelled sheet 1 of 12, top left I think PA10 can only be USART1_RX, but is labelled USART1_TX

https://github.com/PX4/Hardware/blob/master/FMUv2/PX4FMUv2.4.5.pdf

**Comment by davids5** [comment]
Not sure what you are looking at....

**Comment by proficnc** [comment]
Page 1 is the FMU... It is the RX for the IO, and that is exactly how it is labeled

**Comment by kwikius** [comment]
Sorry .. Clearly either I am an idiot or the labelling could be clearer :)

**Comment by davids5** [comment]
No worries...It has been an issue with RS-232 (EIA) since day 1. If I was "EIA" I would have called it TX_TO_ME and RX_FROM_ME :)

**Comment by proficnc** [comment]
That's why I love the SPI method... Master in slave out.. MISO etc...

Every board I lay out, I always panic on this stuff...

That bit could do with an additional net Kable to clear it up.
