### ISSUE TITLE
Pixracer: GPS+Compass cable - needed RX & TX swapping for uBlox m8n 

### ISSUE THREAD

**Issue by olibye** [PX4/Hardware#66]
Hi Guys,
just to let you know that I had to swap the GPS UART RX and TX lines on the PixRacer supplied JST GH to uBlox M8N micro DF13 cable. I found this issue as a result of your excellent wiring diagrams.

This may be specific to this particular component:
https://www.unmannedtechshop.co.uk/mini-ublox-m8n-gps-module-with-compass-for-px4-mini/

**Comment by pkocmoud** [comment]
The cables supplied are for specific models of GPS units only. It is not surprising that some level of re-pinning was required. I am glad you got it up and running.
