### ISSUE TITLE
Question+possible issue

### ISSUE THREAD

**Issue by johnsp1** [PX4/Hardware#75]
I assumed this was a 2 layer board looking at the documentation, but I'm seemingly seeing traces that end  at floating vias?

Say perhaps tracing IO-LED_BLUE or IO-LED_AMBER from the smaller F1 ARM to U703? I'm seeing these paths end at vias floating on the opposite side of the board

Apologies for the beginner question, but is the Pixhawk a 4+ layer board?

**Comment by davids5** [comment]
@johnsp1,

I am not sure what you are looking at.  Grab a copy of [eagle](http://www.autodesk.com/products/eagle/overview) and [the files](https://github.com/PX4/Hardware/tree/master) and you can see how it is routed.
