### ISSUE TITLE
The HMC5983 in FMUv3 

### ISSUE THREAD

**Issue by zouboan** [PX4/Hardware#79]
I bought a pixhawk 2.1 from HEX recently，I 
found that the PCB of FMUv3  i bought is different from https://github.com/PX4/Hardware/tree/master/FMUv3_REV_D
for example:the PCB of FMUv3 have a HMC5983,but what I bought was not included！

**Comment by lumber3** [comment]
HMC5983 is closed product .replaced by new IC

**Comment by pkocmoud** [comment]
The choice of components is determined by the manufacturer and device availability. You should contact the specific manufacturer if you need assistance on this.
