### ISSUE TITLE
help ! px4io not found error  

### ISSUE THREAD

**Issue by mehrdadshiri** [PX4/Hardware#82]
hi every body
i was flying my pixhawk on a quad-copter for the first time and suddenly an alarm came off and and it landed.
so I connected the usb right after and now it says px4io not found in mission planer and the on the Qground control it says "cannot communicate"  . i have read on the net that some people suggest to start with the safety switch pressed for firmware restart and it didn't help at all and the switch is not blinking anymore. 
has anyone had a same experience before or have any suggestions to fix this ?

**Comment by hamididari** [comment]
hi
can you check the px4io micro is health or not (connect to px4io via st link and read memory)

**Comment by pkocmoud** [comment]
@mehrdadshiri - Please seek assistance on this issue from your hardware supplier or the flightstack software's discussion board. http://discuss.px4.io/ for PX4.
