### ISSUE TITLE
the boom of  Pixhawk 2

### ISSUE THREAD

**Issue by caiganggang** [PX4/Hardware#83]
Would you like to tell me the all material list.Especially the connectors model,where could i buy  it ? Think you!

**Comment by proficnc** [comment]
You can purchase Pixhawk 2 from any ProfiCNC reseller

**Comment by kd0aij** [comment]
I think he meant BOM

**Comment by caiganggang** [comment]
yes .I'd like to know the boom of  connectors and  where to buy it
