### ISSUE TITLE
4 crashes without understanding the correct cause

### ISSUE THREAD

**Issue by samiresmaili** [PX4/Hardware#87]
Hello
I have four flights that have led to a fall. One of them is in altitude mode, for which an alert has been recorded at the moment of imbalance and three of them are in mission mode, for which there is no error for them at the moment of imbalance. To understand the cause of the crashes, Please help me.
Altitude flying number 1: there is initially a registered warning shown in the image below and an error at the moment of crash. What should you do to fix this error?
 
![image](https://user-images.githubusercontent.com/36726627/39801897-e8689230-5381-11e8-8433-0b734dc6d734.png)

Flight 2: a warning was initially recorded, but nothing has been recorded at the moment of the crash. Full information on the log
![image](https://user-images.githubusercontent.com/36726627/39801972-1a483080-5382-11e8-83e4-23655e648dd9.png)
 
flight 3: no warning or error has been given at the moment of crash. Full information on the log.
 
![image](https://user-images.githubusercontent.com/36726627/39802010-2e82263c-5382-11e8-9848-08c697757ddc.png)

flight 4: no warning or error has been given at the moment of crash. Full information on the log.
![image](https://user-images.githubusercontent.com/36726627/39802036-422dc1b4-5382-11e8-91e5-e01b1698142c.png)

flight 1: https://review.px4.io/plot_app?log=0e0f0aaf-5c42-480e-9d62-e08dfb70a891
flight 2: https://review.px4.io/plot_app?log=9194034e-8b81-4026-a421-0a1ca49f21e7
flight 3: https://review.px4.io/plot_app?log=4b227795-7069-4809-a804-cadf567e3a32
flight 4: https://review.px4.io/plot_app?log=06c0982d-6c37-4d9a-89d6-1692d3ab2e63

**Comment by pkocmoud** [comment]
@samiresmaili - Please seek assistance on this issue from your hardware supplier or the flightstack software's discussion board. http://discuss.px4.io/ for PX4.
