### ISSUE TITLE
Pixhawk 4 (FMUv5)

### ISSUE THREAD

**Issue by astekachev** [PX4/Hardware#89]
Hi!
I have a couple of questions. 
Will Pixhawk 4 schematics and PCB Project be available for public access in the near future? 
Or Pixhawk 4 is commercial project and the project schematics with PCB Project will be closed? 
Thank you!

**Comment by pkocmoud** [comment]
As I understand it, FMUv4 and FMUv5 designers are only required to release a microcontroller reference pinouts for software compatibility. So you should not expect to find specific schematics or board design files unless the original designer chooses to release them.
