### ISSUE TITLE
Can't find Schematics and Layout of FMUv5

### ISSUE THREAD

**Issue by gcarmix** [PX4/Hardware#92]
Hi, I can't find schematics and layout of FMUv5 is it no more open hardware??

**Comment by pkocmoud** [comment]
@gcarmix - The FMUv5 standard is only provided as an list of pin assignments and their functional descriptions as a reference for software compatibility found here: 

[https://github.com/PX4/Hardware/tree/master/FMUv5](https://github.com/PX4/Hardware/tree/master/FMUv5 )

The circuit design is up to the individual designers and as it is not one of my designs I don't have any additional information.
